pipeline {
    agent any
    environment {
        bbranch ="${Branch}".replace('origin/', '');
    }
    stages {
        stage('git'){
            steps {
                // 
                git branch: "${bbranch}",credentialsId: '003', url: 'ssh://git@git.biyong001.com:10022/coin/developer.git'
                echo "${bbranch}";
                echo Branch;
                // def check_groovy_file="./Jenkinsfile2";
                // load "${check_groovy_file}";
                echo 'git clone';
            }
        }
        stage('build') {
            agent {
                docker { image 'node:12.20.1-stretch' }
            }
            steps {
                sh 'npm --version'
                sh 'sh ./deployments/build.sh'
                echo 'build';
                sh 'sh ./deployments/docker.sh'
                echo 'docker';
            }
        }
        stage('finished') {
            steps {
                sh 'sh ./deployments/finished.sh'
                echo 'docker';
            }
        }
    }
}