pipeline {
    agent any
    environment {
        bbranch ="${Branch}".replace('origin/', '');
    }
    stages {
        stage('git'){
            steps {
                echo "${bbranch}";
                echo Branch;
                echo 'git clone';
            }
        }
        stage('build') {
            agent {
                docker { image 'node:16.19.0' }
            }
            steps {
                sh 'npm --version'
                sh 'sh ./deployments/build.sh'
                echo 'build';
                sh 'sh ./deployments/docker.sh'
                echo 'docker';
            }
        }
        stage('finished') {
            steps {
                sh 'sh ./deployments/finished.sh'
                echo 'docker';
            }
        }
    }
}